rdaum/moor

- .gitignore
- crates/regexpr-binding/build.rs
- crates/regexpr-binding/c_src/regexpr.c
- crates/regexpr-binding/c_src/regexpr.h
Changes language level for C to c2x, rather than leaving as the default. This allows the prototype warning to be fixed (c17 warns that the   calling stye is going away, c2x makes it so). This also allows changing the function definitions from the old K&R style to something modern.
> Remove C error warnings about function prototypes for regexp bindings

- .github/workflows/rust-buiild.yml
- .github/workflows/todo-issues.yml
This will switch to using Node 20 within GitHub Actions and get rid of some warnings about the older stuff being deprecated.
> ci: Update to `actions/checkout` `v4`

- crates/daemon/src/main.rs
Output with `--debug` looks as follows (spoiler for why I needed this):
```
2024-05-25T19:56:20.021697Z DEBUG moor-eventfd-listen moor_rdb::paging::page_storage: crates/rdb/src/paging/page_storage.rs:119: Synced all pages to disk? true
2024-05-25T19:56:20.021730Z DEBUG moor-eventfd-listen moor_rdb::paging::page_storage: crates/rdb/src/paging/page_storage.rs:119: Synced all pages to disk? true
2024-05-25T19:56:20.021762Z DEBUG moor-eventfd-listen moor_rdb::paging::page_storage: crates/rdb/src/paging/page_storage.rs:119: Synced all pages to disk? true
2024-05-25T19:56:20.021795Z DEBUG moor-eventfd-listen moor_rdb::paging::page_storage: crates/rdb/src/paging/page_storage.rs:119: Synced all pages to disk? true
2024-05-25T19:56:20.021827Z DEBUG moor-eventfd-listen …
```
> feat(deamon): added --debug flag

- Cargo.lock
- Cargo.toml
- crates/telnet-host/Cargo.toml
- crates/telnet-host/tests/common/mod.rs
* `daemon` wasn't correctly rebuilt on changes
* `daemon` processes used calling working dir, which led to them implicitly sharing `connections.db`
> Fix bugs in telnet e2e harness

- Cargo.lock
- Cargo.toml
- crates/daemon/src/rpc_server.rs
- crates/db/src/db_loader_client.rs
- crates/db/src/db_tx.rs
- crates/db/src/db_worldstate.rs
- crates/db/src/loader.rs
- crates/db/src/odb/object_relations.rs
- crates/db/src/odb/rb_worldstate.rs
- crates/kernel/src/builtins/bf_properties.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/textdump/load_db.rs
- crates/kernel/src/textdump/write_db.rs
- crates/kernel/src/vm/vm_test.rs
- crates/kernel/tests/textdump.rs
- crates/kernel/testsuite/basic/basic_suite.rs
- crates/values/src/model/mod.rs
- crates/values/src/model/permissions.rs
- crates/values/src/model/propdef.rs
- crates/values/src/model/props.rs
- crates/values/src/model/world_state.rs
Rework and fix how property definitions and values are handled
At some point values and properties got mixed up in how transitive
propagation and resolution was happening. PropDefs were being copied
down the inheritance hierarchy, but not values. Which is opposite of
how LambdaMOO has it.
This meant that bf_properties was returning the set of all properties
defined by parents instead of just the locally defined properties,
which was wrong.
This is a fairly major rework that rewrites things so that:
-  PropDefs exist only on the root of the chain where the property is  defined.
-  Values propagate down the tree.
-  Flags and owners are moved off PropDefs, and are separately defined,   and again propagated down the tree
-  Clearness remains defined by absence of a property value on a given …
> Fix property resolution

- crates/db/src/db_worldstate.rs
- crates/kernel/Cargo.toml
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/vm/activation.rs
- crates/kernel/testsuite/README.md
- crates/kernel/testsuite/basic/basic_suite.rs
- crates/kernel/testsuite/basic_suite.rs
- crates/kernel/testsuite/common/mod.rs
- crates/kernel/testsuite/eval_suite.rs
- crates/kernel/testsuite/regression_suite.rs
- crates/values/src/model/permissions.rs
- crates/values/src/var/mod.rs
This is a huge pile of changes that ends up with: we have solid tests for the `eval()` built-in. Interesting stops along the way:
* Fix the test harness logic for executing code in fake verbs (previously we only ever re-executed the very first command for each call, per db)
* Switch tests from using a fake verb to instead `eval()`
* Add permission checks to `eval()` (both the `bf_eval` and the trampoline implementations)
* Fix clearing `programmer` and `wizard` flags
* Small fixes in built-in variables under `eval`
Each commit should be easy to review on its own. If it helps, I can split this up into self-contained PRs as well.
> Add tests for `eval` built-in

- crates/db-relbox/src/rb_worldstate.rs
- crates/db-wildtiger/src/worldstate/wt_worldstate.rs
- crates/kernel/testsuite/common/mod.rs
- crates/kernel/testsuite/moot_suite.rs
- crates/kernel/testsuite/regression_suite.rs
Also fix smol bugs caught by the test suite while we're at it; they're the same small ones we saw on `relbox` too.
> Run `kernel` test suite against both storage backends

- Cargo.lock
- Cargo.toml
- crates/compiler/src/lib.rs
- crates/kernel/Cargo.toml
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/testsuite/common/mod.rs
- crates/kernel/testsuite/moot/huh.moot
- crates/kernel/testsuite/moot_suite.rs
- crates/values/src/model/mod.rs
Port tests for `huh` from Toast. The main blocker for this was adding support to execute non-`eval` commands to `moot`. To do *that*, we now run through a `Scheduler`, instead of just a VM; the prefix for non-`eval` commands is `%` in `.moot` test files.
PR includes some non-trivial / non-obvious changes. In no particular order:
* Ad-hoc transformation of `CommandExecutionError` into `Var` (for `E_VERBNF`)
* Added `#[source]` annotations to some `thiserror` error variants
* Added `Scheduler::submit_shutdown` to send a `Shutdown` request programatically
* Why: because just calling `scheduler.stop()` makes us wait until `.recv_timeout()` in the main loop times out, slowing tests down considerably
* Don't prune tasks that are finished (i.e. sender channel is closed) but still have …
> test(moot): `huh` using `Scheduler` in tests

- Cargo.lock
- Cargo.toml
- crates/daemon/src/rpc_server.rs
- crates/db-wildtiger/src/wtrel/db.rs
- crates/db-wildtiger/src/wtrel/relation.rs
- crates/kernel/Cargo.toml
- crates/kernel/benches/vm_benches.rs
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/builtins/mod.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/task_messages.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/vm/vm_execute.rs
- crates/relbox/Cargo.toml
- crates/relbox/src/index/mod.rs
- crates/relbox/src/paging/backing.rs
- crates/relbox/src/paging/cold_storage.rs
- crates/relbox/src/tx/transaction.rs
- crates/relbox/src/tx/working_set.rs
Three related things:
* Eliminates the use of `subscribe_to_task` because this was a) overengineered and b) leading to race conditions if the task completed before the subscription attempt
* Switch to `oneshot` crate from kanal from the kanal::oneshot usage and thereby be able to use its `recv_timeout` function and then make tests use that so they can't hang forevers.
* Rip out remaining use of `kanal` as this crate seems mainly abandoned and crossbeam is already in the dependency hierarchy. I'm not in love with crossbeam, but it will do, and it's reliable and maintained. (Over time I will be deprecating a lot of the channel usage in the scheduler anyways).
> Remove task "subscriptions" and switch from `kanal` to crossbeam (again)

- crates/kernel/src/builtins/bf_list_sets.rs
- crates/kernel/src/builtins/bf_num.rs
- crates/kernel/src/builtins/bf_objects.rs
- crates/kernel/src/builtins/bf_properties.rs
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/builtins/bf_strings.rs
- crates/kernel/src/builtins/bf_values.rs
- crates/kernel/src/builtins/bf_verbs.rs
```
E_ARGS      Incorrect number of arguments
E_INVARG    Invalid argument
```
We're raising `E_INVARG` where we should instead raise `E_ARGS`. I've been fixing these as they're caught by test cases, but 1. I'm not sure they'll *all* be covered by tests ever, and 2. let's just get through them all in one go.
_If this PR changes any `E_INVARG` that is *not* about "wrong number of arguments", then that is a mistake_
> The great `E_INVARG` purge of '24

- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/vm/exec_state.rs
- crates/kernel/src/vm/vm_execute.rs
The logic to aportion and then account for used ticks in the execution loop was broken. This is what was breaking long running tasks like e.g. "help intro."
At some point in some refactor I must have confused the idea of `tick_slice` with `max_ticks` and the counting of the used ticks for the task as a whole was being mixed up with the ticks for the current pass through the execution loop. And so tasks were running forever not being killed for hitting max count, but also treated further down as if they had no ticks.
> fix: task tick slicing logic

- Cargo.lock
- crates/kernel/Cargo.toml
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/vm_host.rs
Didn't fully diagnose why, but the scheduler `dashmap` tasks map was deadlocking when returning from a read.
Switching back to a mutex'd hashmap fixes the problem.
> Fix deadlock from `bf_read`

- Cargo.toml
- crates/daemon/Cargo.toml
- crates/daemon/src/main.rs
- crates/daemon/src/rpc_server.rs
- crates/db-wiredtiger/build.rs
- crates/db-wiredtiger/src/bindings/connection.rs
- crates/db-wiredtiger/src/bindings/cursor.rs
- crates/db-wiredtiger/src/bindings/session.rs
- crates/db-wiredtiger/src/lib.rs
- crates/db-wiredtiger/src/worldstate/wt_worldstate.rs
- crates/db-wiredtiger/src/wtrel/mod.rs
- crates/db-wiredtiger/src/wtrel/rel_db.rs
- crates/db-wiredtiger/src/wtrel/rel_transaction.rs
- crates/db/Cargo.toml
- crates/db/src/lib.rs
- crates/kernel/Cargo.toml
- crates/kernel/src/vm/vm_test.rs
- crates/kernel/tests/textdump.rs
- crates/kernel/testsuite/common/mod.rs
- crates/kernel/testsuite/moot_suite.rs
- crates/kernel/testsuite/regression_suite.rs
Makes it so by default moor is built without my in-house experimental/unfinished in-memory "relbox" database backend.
> Put "relbox" behind a `feature`

- Cargo.lock
- Cargo.toml
- crates/kernel/Cargo.toml
- crates/kernel/src/builtins/bf_strings.rs
The `crypt-sys` crate ended up being a problem if we want to compile on MacOS (or other non-Linux environments).
Also a slight tweak to MD5 dep to get rid of one of the duplicated dependencies that pwhash was introducing.
> Rollback to using `pwhash` crate for `bf_crypt`

- crates/db/src/db_worldstate.rs
- crates/kernel/src/builtins/bf_objects.rs
- crates/kernel/src/builtins/bf_properties.rs
- crates/kernel/testsuite/moot/create.moot
- crates/kernel/testsuite/moot/recycle.moot
- crates/kernel/testsuite/moot_suite.rs
- crates/moot/Test.db
- crates/moot/src/lib.rs
- crates/moot/tests/moot_lmoo.rs
- crates/values/src/model/mod.rs
* Verified this passes against MOO-1.8.1
* We have some failures against `moor`. First one:
```
assertion failed: `(left == right)`: Line 18: recycle($nothing);
Diff < left / right > :
<E_INVIND
>E_INVARG
```
> test: port `recycle` tests from Stunt

- crates/compiler/src/codegen.rs
- crates/compiler/src/codegen_tests.rs
- crates/compiler/src/decompile.rs
- crates/compiler/src/opcode.rs
- crates/compiler/src/program.rs
- crates/kernel/src/vm/activation.rs
- crates/kernel/src/vm/vm_call.rs
- crates/kernel/src/vm/vm_execute.rs
- crates/values/src/var/list.rs
These counts weren't necessary, because they can be derived from the content of the opcode itself.
> Remove redundant fields from scatter opcode

- crates/kernel/src/tasks/scheduler.rs
Puts the Task list and the set of pending input requests in one single `Inner` in an `RwLock` instead of two separate locks.
There was at least the potential for deadlock here.
> Scheduler: Consolidate `input_requests` and `tasks` behind one lock

- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/task_messages.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/vm/exec_state.rs
- crates/kernel/src/vm/vm_call.rs
**Sorry this one is going to be hard to read as any kind of diff. If you're worried, I recommend just reading the whole of scheduler.rs and task.rs. **
Highlights:
* Suspended tasks no longer hog a thread and idle. Instead their thread ends and they are moved into a suspended vector inside the scheduler itself.
* Tasks that start in a delayed state (e.g. forks) now no longer use a thread with a manual delay. Instead they begin their life in suspended state and are picked up by the scheduler tick.
* Gut the remainder of the complicated dispatch logic that was leftover from the old async/tokio version of this code. Intermediate result objects (which used to be processed in batch) are gone, and actions are immediately acted on. This should be a lot easier to read now.
I believe this paves …
> Major refactoring of Scheduler/Task

- Cargo.lock
- Cargo.toml
- crates/kernel/Cargo.toml
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/task_messages.rs
* Load bg_ticks, fg_ticks, bf_seconds, fg_seconds, max_stack_depth from $server_options if they're there.
* Held in an ArcSwap<> on Scheduler, and passed in to each task.
* `bf_load_server_options` refreshes
> Implement support for $server_options for ticks/seconds/stack

- crates/kernel/testsuite/moot_suite.rs
- crates/moot/src/lib.rs
- crates/moot/tests/moot_lmoo.rs
- crates/telnet-host/src/main.rs
- crates/telnet-host/tests/integration_test.rs
In one terminal, start `moor-telnet-host` and leave it running:
```console
[abesto@keyrit-desktop moor]$ cargo run -p moor-telnet-host
```
Attempting to start `moor-telnet-host` results in the new `moor-telnet-host` exiting cleanly with status 0:
```console
[abesto@keyrit-desktop moor]$ cargo run -p moor-telnet-host
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/moor-telnet-host`
2024-06-26T22:15:26.478132Z  INFO main moor_telnet_host: crates/telnet-host/src/main.rs:87: Host started.
2024-06-26T22:15:26.478236Z  INFO main moor_telnet_host: crates/telnet-host/src/main.rs:90: ZMQ client loop exited, stopping...
2024-06-26T22:15:26.478274Z  INFO main moor_telnet_host: crates/telnet-host/src/main.rs:99: Done.
[abesto@keyrit-desktop moor]$ echo $?
0 …
```
> fix(telnet-host): properly crash; crash fails tests

- crates/daemon/src/rpc_server.rs
- crates/moot/src/lib.rs
- crates/telnet-host/src/main.rs
- crates/telnet-host/src/telnet.rs
- crates/telnet-host/tests/integration_test.rs
For https://github.com/rdaum/moor/issues/342
* Switch to zmq IPC sockets for daemon/host with a UUID in the path to avoid conflict
* Dynamically choose the telnet listening port based on what's available
> Make the integration network hermetic

- crates/console-host/src/main.rs
- crates/daemon/src/main.rs
- crates/telnet-host/src/main.rs
- crates/web-host/src/main.rs
Switches the default binding for the ZMQ connections to use ipc://
90% of the time we'll be running these things on the same host. The option is still there to use tcp:// if not.
> Default to ZMQ IPC sockets for RPC connections

- crates/daemon/src/main.rs
- crates/daemon/src/rpc_server.rs
- crates/daemon/src/tasks_wt.rs
- crates/db-wiredtiger/src/bindings/session_config.rs
- crates/db-wiredtiger/src/lib.rs
- crates/kernel/benches/vm_benches.rs
- crates/kernel/src/lib.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/sessions.rs
- crates/kernel/src/tasks/suspension.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/tasks_db.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/vm/activation.rs
- crates/kernel/src/vm/exec_state.rs
- crates/kernel/src/vm/vm_execute.rs
- crates/kernel/testsuite/moot_suite.rs
- crates/values/src/model/verb_info.rs
Initial WiredTiger tasks DB implementation
This is a series of commits which pileup to implement persistent task save and load (on server restart). This is a feature that LambdaMOO has, allowing it to resume background tasks between server restarts, and is required for us to be at feature parity with 1.8.0.
Successfully persists stored tasks, and reconstitutes them on restart of the server.
Caveats:
.
- Implementation is for WiredTiger only, no Relbox yet
- The actual save/commit for each task currently blocks the Scheduler thread, and so could be a performance problem in the future that we will need to address by putting it into its own background thread.
- No tweaking has been done on the wiredtiger DB configuration to e.g. commit more cache and keep more memory resident, etc.
- No task …
> Persistent tasks database implementation

- crates/telnet-host/tests/moot/suspend_read_notify.moot
The test as written *should* fail; we don't currently have a way in `moot` to send input after some delay. Doesn't seem worth adding that feature at the moment (or maybe ever), so: delete the commented-out test.
> chore: delete disabled test that *shouldn't* work

- crates/telnet-host/src/telnet.rs
- crates/telnet-host/tests/integration_test.rs
- crates/telnet-host/tests/moot/huh.moot
I couldn't understand that.
Fixes #340
> fix(telnet,rpc_server): fix default `huh` message

- Cargo.lock
- crates/console-host/Cargo.toml
- crates/console-host/src/main.rs
- crates/daemon/src/rpc_server.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/suspension.rs
- crates/kernel/src/vm/moo_execute.rs
- crates/telnet-host/src/main.rs
- crates/telnet-host/src/telnet.rs
- crates/values/src/tasks/errors.rs
- crates/values/src/tasks/mod.rs
* Signal handling for `console-host` and `telnet-host` to properly exit on `SIGTERM`/`SIGINT`
* Get rid of `TaskResult` which was a redundant vestige better expresses with `Result<Var, SchedulerError>`
> A couple more cleanups

- crates/console-host/src/main.rs
- crates/daemon/src/main.rs
- crates/kernel/benches/vm_benches.rs
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/builtins/mod.rs
- crates/kernel/src/config.rs
- crates/kernel/src/tasks/mod.rs
- crates/kernel/src/tasks/scheduler.rs
- crates/kernel/src/tasks/task.rs
- crates/kernel/src/tasks/vm_host.rs
- crates/kernel/src/textdump/mod.rs
- crates/kernel/src/vm/mod.rs
- crates/kernel/src/vm/vm_call.rs
- crates/telnet-host/src/telnet.rs
- crates/values/src/tasks/events.rs
- crates/web-host/src/host/ws_connection.rs
Makes room for sending things other than just text to the client by allowing (in non-strict-compat mode) the `notify` builtin to send _any_ MOO value to the client, not just a string.
For the existing old-school telnet host if this is a string, it outputs as usual. Otherwise it gets printed in its literal representation.
For the web host, everything is turned into its JSON equivalent.
> Allow "rich" host/client output

- crates/console-host/src/main.rs
- crates/kernel/src/builtins/bf_server.rs
- crates/kernel/src/tasks/task.rs
- crates/telnet-host/src/telnet.rs
- crates/values/src/tasks/events.rs
- crates/web-host/src/host/ws_connection.rs
Adds an extra optional argument to `notify` that can identify the content-type to the host.
> Support for sending a content-type via notify

- crates/compiler/src/decompile.rs
- crates/compiler/src/moo.pest
- crates/compiler/src/names.rs
- crates/compiler/src/parse.rs
- crates/compiler/src/unparse.rs
- crates/kernel/src/vm/vm_test.rs
Lets scatter assigns take part in lexical scoping.
https://github.com/rdaum/moor/issues/281
> Support let/const bindings for scatter-assign

- Cargo.lock
- crates/kernel/testsuite/moot/create.moot
- crates/kernel/testsuite/moot_suite.rs
- crates/telnet-host/tests/moot/suspend_read_notify.moot
- crates/testing/moot/Cargo.toml
- crates/testing/moot/README.md
- crates/testing/moot/src/lib.rs
- crates/testing/moot/src/moot.pest
- crates/testing/moot/src/parser.rs
- tools/moot-lang/syntaxes/moot.tmLanguage.json
The original hand-built parser had a bunch of weird behaviors around comments and missing / present empty lines & line endings, and was kinda fragile in general. This should make everything better (?)
> [moot] Rebuild custom parser in `pest`

- crates/telnet-host/tests/integration_test.rs
- crates/testing/moot/src/lib.rs
- crates/testing/moot/src/telnet.rs
- crates/testing/moot/tests/moot_lmoo.rs
* Moved the Telnet implementation of `trait MootRunner` into its own file
* Cleaned up the code around executing `moot` tests
* Small fix: #386 stopped calling `validate_state` between the test command and the expectations. This PR restores that call.
* Small improvement: test assertion failure messages now include `{path}:{line_no}`; this string can be Ctrl-Clicked in VSCode to go directly to the failed assertion in the `.moot` file!
> refactor(moot): only clean, no confusion

- crates/kernel/testsuite/moot/objects/test_parent_chparent.moot
- crates/testing/moot/src/lib.rs
- crates/testing/moot/tests/moot_lmoo.rs
- tools/moot-translate.awk
... and some stuff I used to do it, because as discussed, I wish stacked PRs would exist but they don't.
This new test passes against both Lambda and `moor`.
> test: migrate `test_parent_chparent`

- crates/db/src/db_transaction.rs
- crates/kernel/testsuite/moot/objects/test_properties_and_inheritance.moot
- crates/kernel/testsuite/moot_suite.rs
- crates/testing/moot/tests/moot_lmoo.rs
- tools/moot-translate.awk
**Look at the `fix` commit very very carefully.** This fix makes the assumption that propdefs only exist on the objects that actually had the property directly added to them (and so inheritance resolution takes place at read time). If this is *not* the case, then this "fix" hides the real problem (the real problem being that the propdef is not pushed to somewhere it *should* be). In this case it's also concerning that this is not caught by anything else in the added tests.
FTR, failure before the `fix` commit:
```
MootBlockSpan { line_no: 180, expr: Test(MootBlockTest { kind: Eval, prog_lines: ["return $n.c;"], expected_output: [MootBlockTestExpectedOutput { expected_output: "player.location", verbatim: false, line_no: 181 }] }) }
#3 >> ; return $n.c; "moot-line:180";
#3 << #2
#3 >> ; …
```
> test: migrated `test_properties_and_inheritance`

- Cargo.lock
- crates/kernel/Cargo.toml
- crates/kernel/testsuite/moot_suite.rs
- crates/telnet-host/Cargo.toml
- crates/testing/moot/Cargo.toml
- crates/testing/moot/src/lib.rs
- crates/testing/moot/src/stylesheet.rs
- crates/testing/moot/src/telnet.rs
This should make it much easier to skim `moot` test output. Does for me, anyway!
Against real LambdaMOO, with LambdaMOO logs interspersed (`crates/testing/moot/tests/moot_lmoo.rs`)
Against mooR, with mooR server logs interspersed (`crates/telnet-host/tests/integration_test.rs`)
> feat(moot): optional colored output

- crates/telnet-host/tests/integration_test.rs
These integration tests are frequently slow. One guess for why is: we (re)build the binaries under test as part of the test (not as part of the build).
This PR eliminates one of the builds always cleanly, and eliminates the other most of the time with a horrible hack (see code comments).
> fix(telnet-host/tests): Use existing binaries

- crates/kernel/src/builtins/bf_server.rs
Surely the smallest PR ever.
Makes the value (second arg to resume) optional as intended, and adds a syntax comment.
I'd also like to write a moot test to show a pass after the fix but don't understand enough to yet. Happy to add with another commit.
> Fix the resume() builtin so the second arg is optional

- crates/web-host/src/client/narrative.ts
This PR adds basic support for automatically speaking text as it arrives in the output window of the web host.
Note that the user's typed text is announced as well (as it appears in the output); this seems ok to me for a first attempt, perhaps we make this more complex later with some client setting to choose not to announce input.
The role here is set to log, and atomic is false to only announce added text, rather than speaking the entire window each time.
> Add ARIA live region to output window so text is auto-spoken by screen readers

- crates/common/src/model/defset.rs
- crates/common/src/model/world_state.rs
- crates/db/src/db_worldstate.rs
- crates/db/src/moor_db_tests.rs
- crates/db/src/ws_transaction.rs
- crates/kernel/src/vm/builtins/bf_objects.rs
- crates/kernel/testsuite/moot/objects/test_clear_properties.moot
- crates/kernel/testsuite/moot/objects/test_various_things_that_can_go_wrong.moot
- crates/kernel/testsuite/moot_suite.rs
- crates/testing/moot/tests/moot_lmoo.rs
- crates/var/src/error.rs
There may be a more optimal way to do the property check? I couldn't find it by just reading the code (around) `Defs`.
> Migrate more `test_objects.rb` tests from Stunt

- Cargo.lock
- crates/common/src/program/mod.rs
- crates/common/src/program/names.rs
- crates/common/src/program/opcode.rs
- crates/compiler/Cargo.toml
- crates/compiler/src/codegen.rs
- crates/compiler/src/codegen_tests.rs
- crates/compiler/src/decompile.rs
- crates/compiler/src/lib.rs
- crates/compiler/src/parse.rs
- crates/compiler/src/unparse.rs
- crates/compiler/src/var_scope.rs
- crates/daemon/src/rpc_server.rs
- crates/kernel/src/vm/builtins/bf_objects.rs
- crates/kernel/src/vm/builtins/bf_properties.rs
- crates/kernel/src/vm/builtins/bf_server.rs
- crates/kernel/src/vm/builtins/bf_verbs.rs
- crates/kernel/src/vm/builtins/mod.rs
- crates/kernel/src/vm/moo_execute.rs
- crates/kernel/src/vm/moo_frame.rs
- crates/kernel/src/vm/vm_call.rs
- crates/kernel/src/vm/vm_test.rs
- crates/kernel/testsuite/moot/objects/test_various_things_that_can_go_wrong.moot
Gets rid of the use of the bitmasked variable scope with stretchy
environment.
Pushes and pops whole scopes at a time.
v_none() / TYPE_NONE indicates E_VARNF, like in LambdaMOO
Fixes some long standing issues with offsets for scopes being
completely wrong in some cases.
Still some niggling issues with decompilation, to restore the original
variable state at scope time, which is going to be tricky to resolve.
>     Rework variable scope management completely

- book/src/the-moo-programming-language/built-in-functions/crypto.md
- book/src/the-moo-programming-language/built-in-functions/extensions.md
* Moves the age builtins to the moor section of extensions.md
* Add them to crypto.md with examples
> Improve age encryption docs in Moor book

- book/build-single-page.sh
**N.B.:** the rendering pipeline is *completely* different from normal `mdbook` rendering, so do *not* use this to verify formatting, even vaguely.
```sh
cd book
./build-single-page.sh --html
```
Output ends up, relative to the repo root, in: `book/book/pandoc/{html,pdf}/moor.{html,pdf}`
> feat(book): build single HTML, PDF output
